// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateLicense(arg1:string):Promise<main.ActivationResult>;

export function GetDriveTypeInfo():Promise<main.DriveTypeInfo>;

export function GetLicenseStatus():Promise<main.LicenseStatus>;

export function GetMachineCode():Promise<string>;

export function GetRuntimeInfo():Promise<main.RuntimeInfo>;
