// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateLicense(arg1) {
  return window['go']['main']['App']['ActivateLicense'](arg1);
}

export function GetDriveTypeInfo() {
  return window['go']['main']['App']['GetDriveTypeInfo']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetMachineCode() {
  return window['go']['main']['App']['GetMachineCode']();
}

export function GetRuntimeInfo() {
  return window['go']['main']['App']['GetRuntimeInfo']();
}
